ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Architecture Constraints


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Any requirement that constraints software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)


.Further Information

See https://docs.arc42.org/section-2/[Architecture Constraints] in the arc42 documentation.

****
endif::arc42help[]
[options="header",cols="1,2"]
|===
|Constraints|Background and/or motivation
| Coding guidelines | Because we are an international company, we have to use the companies coding guidelines, to easily swap developers in and out of the project and be consistent

| Must run in Kubernetes | To achieve maximum reliability and scalability, has to be containerized and deployed on a global scale
| English documentation | Everything must be documented in English, so every international development team can understand it. 
| Pixlr integration | Pixlr is currently the tool planned to be integrated as our photo editing platform.
| Testing | Use Testdriven development to keep a high test coverage (at least 90%) with Unit-Tests, and further Integration-, E2E- and Chaos Engineering-Testing.
|===