ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.

.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]

[options="header",cols="1,2"]
|===
|Goal/Requirements| Architectural Approach|
Maximize scalability and innovation to become a market leader | Microservices with the goal of Continuous Deployment 
| Runs everywhere high performance and use the advantages of microservices| Frontend: Web APP mit flutter + dart, Backend: Springboot + Java for API server, DB: general Data Storage: PostgresDB Image-Storage: Data Buckets (S3, etc.)DevOps 
| Fast global application | Cloud deployment distributed across various locations worldwide 
| Continuous Deployment | ReliabilTesting Strategies: TDD, A/B-Testing, Chaos-Engineeringity 
|===
