ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== RV_1 Image Upload

image::../../images/SWARC_Runtime_Image_Upload.drawio.svg[Runtime Diagram of the image upload flow]

. Authenticated user calls **upload** endpoint
. **Image controller** maps / validates request and image data
. **Image service** splits image from metadata and sends them to **message broker**
. **Image-Processing** service recceives image and tries to send it to **object storage**
. If successful receives **link to stored image** and sends it to **message broker**
. **Image repository** now has required data and **stores metadata and file link** in database
. Transaction was successful and user receives a success message

* In case of object storage being unavailable the system tries to retry action with exponential backoff. If retries are exhausted user is informed of the failed transaction.

=== RV_2 Image Search 

image::../../images/SWARC_Runtime_Image_Search.drawio.svg[Runtime Diagram of the image search flow]

. Authenticated user calls **search** enpoint
. **Image controller** maps validates request parameters and forwards it to **Image Service**  
. Search request is sent to **Search Service** via **message broker**
. **Elastic Search** service executes search and returns results to **Search Service** 
. **Image Service** receives results and retrieves image metadata from **Image Repository**
. Results get returned to user

* In case of elastic search being unavailable the system will use exponantial backoff to retry the action. The user is informed of the failed action if retries are exhausted