ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Quality Requirements


ifdef::arc42help[]
[role="arc42help"]
****

.Content
This section contains all relevant quality requirements. 

The most important of these requirements  have already been described in section 1.2. (quality goals), therefore they should only be referenced here.
In this section 10 you should also capture quality requirements with lesser importance, which will not create high risks when they are not fully achieved (but might be _nice-to-have_).

.Motivation
Since quality requirements will have a lot of influence on architectural decisions you should know  what qualities are really important for your stakeholders, in a specific and measurable way.


.Further Information

* See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.
* See the extensive https://quality.arc42.org[Q42 quality model on https://quality.arc42.org].

****
endif::arc42help[]


=== Quality Tree

_Note: The (QG_X) in the following table correspond to top level quality requirements from_ <<Quality Goals>>.

image::../../images/SWARC_Quality_Tree.drawio.svg[Quality Tree Diagram]

ifdef::arc42help[]
[role="arc42help"]
****

.Content
An overview or summary of quality requirements. 


.Motivation
Often we encounter dozens (or even hundreds) of detailed quality requirements. 
In this overview section you should try to summarize, e.g. by describing categories or topics (as suggested by https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-2:v1:en[ISO 25010:2023] or https://quality.arc42.org[Q42])

If these summary descriptions are already precise, specific enough and measurable, you may skip section 10.2.

.Form
Use a simple table in which each line contains a category or topic and a short description of the quality requirement.
Alternatively, you may use a mindmap to structure these quality requirements.
In literature, the idea of a _quality attribute tree_ has also been described, which puts the generic term "quality" as the root and uses a tree-like refinement of the term "quality". 
[Bass+21] introduced the term "Quality Attribute Utility Tree" for this purpose.



****
endif::arc42help[]


=== Quality Scenarios

ifdef::arc42help[]
[role="arc42help"]
****

.Content
Quality scenarios make quality requirements concrete and allow to decide whether they are fulfilled (in the sense of acceptance criteria).
Ensure that your scenarios are specific and measurable.



Two kinds of scenarios are especially useful:

* _Usage scenarios_ (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. 
This also includes scenarios that describe the system’s efficiency or performance. 
Example: The system reacts to a user’s request within one second.
* _Change scenarios_ describe the desired effect of a modification or extension of the system or of its immediate environment. 
Example: Additional functionality is implemented or requirements for a quality attribute change, and the effort or duration of the change is measured.


.Form

Typical information for detailed scenarios include the following:

In short form (favoured in the Q42 model):

* **Context/Background**: What kind of system or component, what is the envirionment or situation?
* **Source/Stimulus**: Who or what initiates or triggers a behaviour, reaction or action.
* **Metric/Acceptance Criteria**: A response including a _measure_ or _metric_


The long form of scenarios (favoured by the SEI and [Bass+21]) is more detailed and includes the following information:

* **Scenario ID**: A unique identifier for the scenario.
* **Scenario Name**: A short, descriptive name for the scenario.
* **Source**: The entity (user, system, or event) that initiates the scenario.
* **Stimulus**: The triggering event or condition the system must address.
* **Environment**: The operational context or condition under which the system experiences the stimulus.
* **Artifact**: The building-blocks or other elements of the system affected by the stimulus.
* **Response**: The outcome or behavior the system exhibits in reaction to the stimulus.
* **Response Measure**: The criteria or metric by which the system’s response is evaluated.


.Examples
See https://quality.arc42.org[the Q42 quality model website] for detailed examples of quality requirements.

.Further Information

* Len Bass, Paul Clements, Rick Kazman: "Software Architecture in Practice", 4th Edition, Addison-Wesley, 2021.

****


endif::arc42help[]


==== SC_1: Mocks exist for 80% of services

.*Context*

Mocks are fake objects which can be used during development to "mock" services.
They are also used a lot for unit and integration testing.

.*Trigger*

A tester needs to mock a service for a new integration test.

.*Acceptance Criteria*

- For 80% of the services mocks should be available.

==== SC_2: App available on 80% of devices

.*Context*

The application should be available worldwide and be installable on a variety of devices.

.*Trigger*

A user installs or opens the application/website.

.*Acceptance Criteria*

- The app can be installed and runs on at least 80% of the active global device market share.


==== SC_3: Failed-deployment rollback after 60 seconds

.*Context*

When errors occur because of a deployment, the impact should be kept to a minimum to prevent big cascading issues.

.*Trigger*

The deployment of a new version fails.

.*Acceptance Criteria*

- The deployment is automatically aborted and a rollback is triggered, restoring the service to the previous known good state.
- The last stable version is restored within 60 seconds of the failure detection.

==== SC_4: Replica creation if CPU load >80%

.*Context*

The application uses Kubernetes for a scaling architecture. In case of high load, more services should be automatically created to handle the load and prevent performance degradation.

.*Trigger*

The CPU load of a service exceeds specified threshold. 

.*Acceptance Criteria*

- Automatically provision additional replicas if the CPU load exceeds 80%.
- Replicas are provisioned and begin accepting traffic within 60 seconds.

==== SC_5: Disable feature within 15 seconds

.*Context*

New features are added quiet often, which sometimes cause issues.
These features should then be easily disableable. 

.*Trigger*

A system administrator decides to disable a certain feature, because it is causing issues.

.*Acceptance Criteria*

- The feature should be completely disabled if the corresponding feature flag is flipped to "disabled".
- This feature flag change should be propagated to all active user sessions within 15 seconds.
