ifndef::imagesdir[:imagesdir: ../images]

[[section-glossary]]
== Glossary

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms


.Form

A table with columns <Term> and <Definition>.

Potentially more columns in case you need translations.


.Further Information

See https://docs.arc42.org/section-12/[Glossary] in the arc42 documentation.

****
endif::arc42help[]

[cols="e,2e" options="header"]
|===
|Term |Definition

|2FA
|<definition-2>

|Apache Kafka
|<definition-2>

|Cloud
|<definition-2>

|Dart (Language)
|<definition-2>

|Elastic Search
|<definition-2>

|Flutter
|<definition-2>

|HashiCorp Vault
|<definition-2>

|Kubernetes
|<definition-2>

|Message Broker
|<definition-1>

|Metadata
|<definition-1>

|Microservices
|<definition-1>

|MongoDB
|<definition-2>

|Pixlr
|<definition-2>

|===
